# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GifMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GifMaker
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'SwiftyGif'

end
